### ISSUE TITLE
Unable to launch Aeon Ubuntu 22.04

### ISSUE THREAD

**Issue by nickmi** [leinelissen/aeon#339]
Hi there,

After installing Aeon using the latest deb package i am unable to launch it, after opening Aeon from terminal i get the following errors

![image](https://user-images.githubusercontent.com/2481323/171724155-458655fc-e3e1-406c-b7b9-de1fac6f5d30.png)

Any help appreciated

**Comment by leinelissen** [comment]
Hey @nickmi! Thanks for the report. I was able to replicate the issue. This is because older builds of a dependency we use (Nodegit) are compiled rather than linked in an old version. This is resolved with the latest version of Nodegit. I will try and release this over the weekend so you can get started!

**Comment by leinelissen** [comment]
Hey @nickmi. I've just released a new version which should address this issue. You can download the new version here: https://github.com/leinelissen/aeon/releases/tag/v0.2.19. I'll close the issue for now, but let me know if this fixes the problem for you.
